### ISSUE TITLE
Make secrets created by Secrets Manager work with KServe/KFServing Service Account

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#143]
**Is your feature request related to a problem? Please describe.**
KFServing/KServe allows you to use a Service Account that references a secret in order to pull a model stored on S3 for inference.  
By default KFServing/KServe expects the secrets keys to be `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` but the keys created from the secrets created by the Secrets Manager integration are `accesskey` and `secretkey`.  
This results in KFServing/KServe (the storage initializer) being unable to pull the model from S3.  

**Describe the solution you'd like**
We should use Kustomize and add an overlay to edit the `inferenceservice` definition to change the key names.  
I will create a separate PR on KServe doc to update it for aws.

**Comment by surajkota** [comment]
We need to investigate using the https://awslabs.github.io/kubeflow-manifests/docs/component-guides/profiles/#profile-plugins feature for this

https://github.com/kserve/kserve/issues/2113

**Comment by surajkota** [comment]
@AlexandreBrown WIP on KServe side for IRSA support, see 2113 for linked PRs but looks like it is already supported. You just need to do a small workaround: https://github.com/kserve/kserve/issues/2003#issuecomment-1053530385

So, the way it would work is, you can use the `awsIamServiceAccount` profile plugin to annotate the `default-editor` service account in user namespace with S3 access and use the workaround mentioned in the issue to attach a secret to the service account. Note: you are not required to use the profile plugin, you can directly annotate any service account with IAM role and use it with KServe, service account is a configurable parameter in InferenceService spec

**Comment by surajkota** [comment]
I would recommend using IRSA and hence closing this issue. Please let us know if you have any more questions
