### ISSUE TITLE
Can we number the sections so that there is no ambiguity 

### ISSUE THREAD

**Issue by akartsky** [awslabs/kubeflow-manifests#16]
In [kubeflow-manifests/examples/aws/cognito-rds-s3/README.md](https://github.com/awslabs/kubeflow-manifests/blob/v1.3-branch/examples/aws/cognito/README.md) can we number the subsections as `4.1` instead of just `1`
so that there is no ambiguity

**Comment by goswamig** [comment]
Also `upto` means including this step. @surajkota

**Comment by surajkota** [comment]
addressed in #19
