### ISSUE TITLE
Add kubeflow related sdk in notebook container.

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#198]
**Is your feature request related to a problem? Please describe.**
We will need to include kubeflow-training sdk and few more sdk which might be present for other component like katib or kserve.
We have only included so far pipeline sdk. 

**Describe the solution you'd like**
for e.g. `pip install kubeflow-training` 
https://github.com/kubeflow/training-operator/tree/master/sdk/python

As a part of this issue, one should also look into other SDK which are present in kubeflow ecosystem.

**Comment by surajkota** [comment]
We added [training sdk](https://pypi.org/project/kubeflow-training/) but looks like we missed [katib](https://pypi.org/project/kubeflow-katib/). Keeping this issue open

**Comment by surajkota** [comment]
All kubeflow related sdks have been added!
