### ISSUE TITLE
Broken link in notebook doc

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#203]
**What is the URL of the document?**
https://github.com/awslabs/kubeflow-manifests/blob/main/docs/component-guides/notebooks.md

**Which section(s) is the issue in?**
![Screenshot_20220422-135511.png](https://user-images.githubusercontent.com/26939775/164769334-5913c47d-61fc-49df-b3f3-9156c0228d25.png)

**What needs fixing and describe the solution you'd like?**
The "here" link is broken

**Comment by rrrkharse** [comment]
What the link should be: https://github.com/awslabs/kubeflow-manifests/blob/main/docs/component-guides/profiles.md

will be fixed in the incoming docs PR: https://github.com/awslabs/kubeflow-manifests/pull/191/files#diff-e8a2714ae926f39e696c8e9d7c4ac1a7a021fe44d07883134132a282928813e4R130
