### ISSUE TITLE
Install and Config Kubeflow on EKS using Terraform

### ISSUE THREAD

**Issue by jianwu-github** [awslabs/kubeflow-manifests#207]
**Is your feature request related to a problem? Please describe.**
Three major working areas when installing and configuring Kubeflow on EKS:
-- Create required AWS Resources, such as S3 Buckets, RDS, AWS Secrets, ...
-- Install Kubernetes Components and Services on EKS
-- Configure and integrate AWS Resources with EKS, such as expose Istio Gateway through AWS ALB/NLB, ...

It would be nice that all these can be done using one IaC tool like Terraform. Also, EKS itself can be created using Terraform too.

**Describe the solution you'd like**
Install and config Kubeflow on EKS using one IaC tool like Terraform 

**Describe alternatives you've considered**
Kustomize is good to deploy Kubernetes Resources, CloudFormation is good to create AWS Resources.

**Additional context**
It might be better if we can use a single IaC tool to install and configure Kubeflow on EKS instead of 2+ tools.

**Comment by jianwu-github** [comment]
Is it possible to support installation of Kubeflow with Terraform based on [AWS EKS Blueprints for Terraform](https://github.com/aws-ia/terraform-aws-eks-blueprints)?

**Comment by surajkota** [comment]
1.6 includes this feature
