### ISSUE TITLE
URL is 404

### ISSUE THREAD

**Issue by narijeong** [awslabs/kubeflow-manifests#212]
**What is the URL of the document?**
https://github.com/awslabs/kubeflow-manifests/blob/main/docs/deployment/cognito/README.md#40-building-manifests-and-deploying-kubeflow

**Which section(s) is the issue in?**
Can't open the URL which is a part of instruction of deploying kubeflow with Conginto
from this page: https://github.com/awslabs/kubeflow-manifests/blob/main/docs/deployment/cognito/README-automated.md

**What needs fixing and describe the solution you'd like?**
Fix it with right URL.

**Additional context**

**Comment by akartsky** [comment]
We are working on the .md files in `main` branch 

For now please use :
- website: https://awslabs.github.io/kubeflow-manifests/docs/deployment/cognito/guide/
or 
- The release branch : https://github.com/awslabs/kubeflow-manifests/tree/release-v1.4.1-aws-b1.0.0/docs/deployment/cognito
