### ISSUE TITLE
namespace label for metrics collector injection

### ISSUE THREAD

**Issue by dewnull** [awslabs/kubeflow-manifests#251]
**Describe the bug**

```
[500] admission webhook "validator.experiment.katib.kubeflow.org" denied the request: 
Cannot create the Experiment "random-experiment" in namespace "kubeflow-person": 
the namespace lacks label "katib.kubeflow.org/metrics-collector-injection: enabled"
```

**Steps To Reproduce**
I had 1.3 installed. I deleted it and reinstalled 1.4 

**Expected behavior**
I was expecting Katib to look for `katib-metricscollector-injection: enabled`
instead of `katib.kubeflow.org/metrics-collector-injection: enabled`

**Environment**
* Kubernetes version 1.20
* Using EKS (yes/no), if so version? Yes
* Kubeflow version 1.4
* AWS build number
* AWS service targeted (S3, RDS, etc.) S3 & RDS

**Additional context**
setting the the new label allows me to submit an experiment via Katib but the runs fail. It looks like the collector is configured correctly.

**Comment by ryansteakley** [comment]
@dewnull Can you additionally share the failed Katib run logs?

**Comment by dewnull** [comment]
I get this from metrics-logger-and-collector

```
flag provided but not defined: -format
Usage of ./file-metricscollector:
  -f string
    	Metric filters
  -m string
    	Metric names
  -o-type string
    	Objective type
  -p duration
    	Poll interval between running processes check (default 1s)
  -path string
    	Metrics File Path
  -s-db string
    	Katib DB Manager service endpoint
  -s-earlystop string
    	Katib Early Stopping service endpoint
  -stop-rule value
    	The list of early stopping stop rules
  -t string
    	Trial Name
  -timeout duration
    	Timeout before invoke error during running processes check
  -w string
    	Whether wait for all other main process of container exiting (default "true")
```

the args to themetrics-logger-and-collector: 

```
    Args:
      -t
      random-test-kf-nldx545x
      -m
      Validation-accuracy;Train-accuracy
      -o-type
      maximize
      -s-db
      katib-db-manager.kubeflow:6789
      -path
      /var/log/katib/metrics.log
      -format
      TEXT
```

so I suspect the issue is with `-format`. Katib [release 0.12](https://github.com/kubeflow/katib/blob/152ec0797c3025d6e4465df0f0654bf3b705fa18/cmd/metricscollector/v1beta1/file-metricscollector/main.go#L107) doesn't have `-format` but [master](https://github.com/kubeflow/katib/blob/91974f1fd5e715a7b69aeecfb3f40d1fe8ca1fbc/cmd/metricscollector/v1beta1/file-metricscollector/main.go#L107) does. 

I wonder if I didn't checkout the correct version of upstream 

@goswamig and @ryansteakley let me know if you still what the webhook and experiment information

**Comment by dewnull** [comment]
after I manually change the image for the katib-controller deployment from`kubeflowkatib/katib-controller`  `kubeflowkatib/katib-controller:v0.12.0` it works fine. I am not sure why Kustomize is not setting the correct tag for the Katie controller image.

**Comment by ryansteakley** [comment]
are you able to run the katib jobs properly now?

**Comment by dewnull** [comment]
yes.
