### ISSUE TITLE
ERROR 1045 (28000): Access denied for user: pod "mysql-client" deleted pod default/mysql-client terminated

### ISSUE THREAD

**Issue by hashtagdata** [awslabs/kubeflow-manifests#258]
ERROR 1045 (28000): Access denied for user:
pod "mysql-client" deleted
pod default/mysql-client terminated (Error)
$ kubectl describe deployment mysql -n kubeflow
Error from server (NotFound): deployments.apps "mysql" not found

**Comment by surajkota** [comment]
@hashtagdata Request you to please use the following link to open an issue and answer the questions asked in the template. This will give us helpful information on the problem you are facing and how we can approach it

https://github.com/awslabs/kubeflow-manifests/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by surajkota** [comment]
Closing this issue since it has been inactive for more than a week. Please reopen with the template linked above incase you need further assistance.
