### ISSUE TITLE
auto rds setup failure

### ISSUE THREAD

**Issue by ran-haim** [awslabs/kubeflow-manifests#277]
Hi,
auto rds setup fails to create rds due to not finding private subnets.
looks like you are looking for a value of "SubnetPrivate" instead of "PrivateSubnet" (maybe changed in aws?)

**Comment by AlexandreBrown** [comment]
Hello @ran-haim , could you give more details on your setup?

Eksctl version, K8s version, etc was it an existing cluster created from an old eksctl version (older version than the prerequisites) ?
