### ISSUE TITLE
Deterministic Installation and Uninstallation of Kubeflow

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#299]
**Is your feature request related to a problem? Please describe.**
#250, #251, #158, https://github.com/kubeflow/manifests/issues/2062, https://github.com/kubeflow/manifests/issues/2096, https://github.com/kubeflow/manifests/issues/2086

**Solutions considered**
https://docs.google.com/document/d/14-ZDDqvqDGrHk2bdZl-JhVIS80z_2jPtxLxWCcfeBKQ/edit#

**Comment by surajkota** [comment]
#250, #251, #158, https://github.com/kubeflow/manifests/issues/2062, https://github.com/kubeflow/manifests/issues/2096, https://github.com/kubeflow/manifests/issues/2086

**Comment by AlexandreBrown** [comment]
That's a great initiative @surajkota 

I always thought it would be nice to be able to take the succesful idea of AWS SAM deployments and apply it to Kubeflow.
Of course AWS SAM is probably not applicable to Kubeflow deployment, but its idea is interesting IMO.

Just like AWS SAM is a Cloud Formation extension, maybe we could have a new Cloud Formation extension for Kubeflow where we have a syntax that generates Cloud Formation like AWS SAM does.

Just a thought tho, I'm not sure how exactly or if it's possible to create a custom Cloud Formation extension like it was done for AWS SAM.

**Comment by surajkota** [comment]
Included initial implementation in 1.6
