### ISSUE TITLE
Pipeline UI can't display s3 Outputs

### ISSUE THREAD

**Issue by kdubovikov** [awslabs/kubeflow-manifests#317]
**Describe the bug**
I can't download any of the pipeline step outputs due to my bucket residing in different region than `us-east-1`.

**Steps To Reproduce**

1. Launch any pipeline
2. Go to Run UI
3. Try to download any output
4. Observe the error: `Failed to get object in bucket [bucket] at path [path]: S3Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting '[actual bucket region]'`

**Expected behavior**

**Environment**
* Kubernetes version
1.21
* Using EKS (yes/no), if so version?
Yes, 1.21

* Kubeflow version

* AWS build number
-

* AWS service targeted (S3, RDS, etc.)
S3

**Screenshots**
<img width="1719" alt="Screenshot 2022-08-08 at 18 16 02" src="https://user-images.githubusercontent.com/832185/183452694-7e46c80e-7007-47b7-9590-072e879ef816.png">
<img width="1727" alt="Screenshot 2022-08-08 at 18 16 17" src="https://user-images.githubusercontent.com/832185/183452741-f63b70cc-f3a2-4168-ba04-a09ebe5c304a.png">

**Comment by kdubovikov** [comment]
Actually, it seems to be an issue with the Kubeflow UI itself. If we look here, https://github.com/kubeflow/pipelines/blob/e8abec24fed4c4f8be6f527207b1cec9811ce3e7/frontend/server/minio-helper.ts#L50, the `region` parameter is not being passed and it is not a part of the artefact API as well. However, MINIO Client API allows you to specify region when creating a client: https://docs.min.io/docs/javascript-client-api-reference.html

**Comment by kdubovikov** [comment]
Just confirmed that this is not a Kubeflow Pipelines issue. Here, we see that API container actually requires the following variable names: 

- `AWS_REGION`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_ACCESS_KEY_ID`

If I add them manually by changing the deployment:

```shell
kubectl edit deployment ml-pipeline-ui-artifact -n kubeflow-user-example-com
```

I see that 

Everything works as expected. That means that easy fix would amount to the following:

- I see that `AWS_SECRET_ACCESS_KEY`, `AWS_ACCESS_KEY_ID` are already added here: https://github.com/awslabs/kubeflow-manifests/blob/259792ab69ab49bf40ece1df026375dd790364e0/awsconfigs/apps/pipeline/s3/aws-configuration-patch.yaml#L18
- That means that we only need to add `AWS_REGION` parameter to the kustomization for everything to work

**Comment by kdubovikov** [comment]
Created a PR to fix this

**Comment by kdubovikov** [comment]
I have re-opened https://github.com/kubeflow/pipelines/issues/8111 since this fix does not seem to solve the issue

**Comment by AlexandreBrown** [comment]
Hey @kdubovikov there is a workaround for viewing S3 artifacts https://github.com/awslabs/kubeflow-manifests/issues/117#issuecomment-1087283762  
Proper support is a WIP from what I understood.

**Comment by kdubovikov** [comment]
Thanks @AlexandreBrown. Closing this issue as a duplicate
