### ISSUE TITLE
failed to create new S3 client: Endpoint: $(kfp-artifact-storage-endpoint) does not follow ip address or domain name standards

### ISSUE THREAD

**Issue by TranThanh96** [awslabs/kubeflow-manifests#336]
**Describe the bug**
I deployed RDS + s3 option.
Follow the doc to verify s3: https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/#42-verify-s3

when running the sample pipeline "[Demo] XGBoost - Iterative model training", a bug occurred: failed to create new S3 client: Endpoint: $(kfp-artifact-storage-endpoint) does not follow ip address or domain name standards

all pods are still running.
![image](https://user-images.githubusercontent.com/26323599/186803526-3dcdfeb6-eb4e-4ead-843a-dff64a3507a6.png)

![image](https://user-images.githubusercontent.com/26323599/186803565-b42a6f0d-d89c-4b1b-b115-ffa1382cc76e.png)

How can I fix that?

**Comment by ryansteakley** [comment]
@TranThanh96 Did the fix, I sent you on slack work for you? We have fixed this in the latest commit.

**Comment by LeoBley** [comment]
@ryansteakley Can I get that fix to or has it been released already?

**Comment by TranThanh96** [comment]
@ryansteakley  It works. Thank you

@LeoBley edit file kubeflow-manifests/awsconfigs/apps/pipeline/s3/config

change `endpoint: $(kfp-artifact-storage-endpoint)` to `endpoint: s3.amazonaws.com`
then apply by running install loop again

**Comment by LeoBley** [comment]
Thanks @TranThanh96 .  

We are now having an issue where the KFP is unable to write tar.gz artifacts to S3 MinIO bucket which isn't found (NoSuchBucket with status code 404).  I'm wondering if we need to make a similar change:
Edit file `kubeflow-manifests/awsconfigs/apps/pipeline/s3/config`
	- change `bucket: $(kfp-artifact-bucket-name)`
	- to `bucket: [bucketName specified in params.env]`
	- then apply by running install loop again

A previous run, with the `endpoint: s3.amazonaws.com` fix you emailed me, wrote a .yaml artifact fine.

**Comment by surajkota** [comment]
Hi everyone, thanks for reporting this issue. We have fixed this and released a patch version https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.5.1-aws-b1.0.2. Please reopen this issue, if you are still facing it
