### ISSUE TITLE
Add a step to config loadBalancerScheme when deploying Load Balancer as Add-on

### ISSUE THREAD

**Issue by jianwu-github** [awslabs/kubeflow-manifests#355]
**What is the URL of the document?**
https://awslabs.github.io/kubeflow-manifests/docs/deployment/add-ons/load-balancer/guide/

**Which section(s) is the issue in?**
"Config Ingress" section in the "Load Balancer" guide

Right now the "Load Balancer" guide did not mention how to config "alb.ingress.kubernetes.io/scheme". The default value is "internet-facing" as in https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/common/istio-ingress/base/params.env 

**What needs fixing and describe the solution you'd like?**
It would be great that a config step can be added to "Config Ingress" section in the "Load Balancer" guide to config the "loadBalancerScheme" to be either "internal" or "internet-facing" 

**Additional context**
Some Kubeflow installations on AWS will be only available internally inside VPC/VPN.

**Comment by surajkota** [comment]
Thanks, we will add this to the docs
