### ISSUE TITLE
[Component Guide] Kubeflow Pipelines

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#36]
We will need to test the KFP SDK on notebook.

One specific point where we might need to add details (documentation, instruction or change) is authentication process of pipeline using KFP sdk. 

More details below.
https://www.kubeflow.org/docs/distributions/aws/pipeline/#s3-access-from-kubeflow-pipelines

**Comment by surajkota** [comment]
1. Create a application/component specific guide for using KFP on AWS
2. Test and update the current documentation if needed

**Comment by surajkota** [comment]
Closing this since we have a pipeline specific guide now, we can track individual feature requests in separate issues now
https://awslabs.github.io/kubeflow-manifests/docs/component-guides/pipelines/
