### ISSUE TITLE
High availability of Kubeflow

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#45]
There are many component of kubeflow which are not highly available.

For e.g. central dashboard has only one replica https://github.com/awslabs/kubeflow-manifests/blob/master/apps/centraldashboard/upstream/base/deployment.yaml#L8

We need to find out all the critical component inside kubeflow and make them highly available.

**Comment by surajkota** [comment]
This issue seems to be related to upstream Kubeflow components and not specific to any of the AWS components. Hence, requesting you to open this upstream for better visibility and tracking in whole community.
