### ISSUE TITLE
create IAM user for S3 access should be part of Prerequisites section, instead of Automated Setup section

### ISSUE THREAD

**Issue by prli** [awslabs/kubeflow-manifests#503]
**What is the URL of the document?**
https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide

**Which section(s) is the issue in?**
Option 2: Manual Setup, step 4.2 [S3]

**What needs fixing and describe the solution you'd like?**
IAM user need to be manually created, but currently the instructions is under the [automated option, step 2](https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/#21-option-1-automated-setup), therefore it would be missed by anyone trying to deploy following the manual section. 

Create IAM user should be moved to the `Prerequisites` section.

**Additional context**
N.A

**Comment by surajkota** [comment]
@prli Thanks for catching it. Would you like to open a PR to fix this?
