### ISSUE TITLE
kubeflow pipeline installation fails . Had to work it around to get through the installation

### ISSUE THREAD

**Issue by harish422** [awslabs/kubeflow-manifests#511]
**Describe the bug**
After installing the kubeflow pipeline with "kubectl apply -k awsconfigs/apps/pipeline/s3" , getting the following error 

error: unable to recognize "awsconfigs/apps/pipeline/s3": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"

**Steps To Reproduce**
1. kubectl apply -k awsconfigs/apps/pipeline/s3
2. After most of the resources are created getting below error:
error: unable to recognize "awsconfigs/apps/pipeline/s3": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"
3. To work around had to deploy below crd first followed by other resources pointing that CRD. Somehow resources are created before CRD creation or parallely causing above error.
    a.  kubectl apply -f upstream/apps/pipeline/upstream/third-party/metacontroller/base/crd.yaml
    b. kustomize build upstream/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user | kubectl apply -f -
    
**Expected behavior**
"kubectl apply -k awsconfigs/apps/pipeline/s3" which is the same step kustomize executes aswell, should install all the resources without any issues.

**Environment**
EKS 1.22 | kubeflow 1.6.1

* Kubernetes version
  1.22 EKS
* Using EKS (yes/no), if so version?
EKS 1.22 
* Kubeflow version
1.6.1
* AWS build number
* AWS service targeted (S3, RDS, etc.)
s3-only

**Screenshots**

**Additional context**
cc @ryansteakley

**Comment by surajkota** [comment]
Hi @harish422, thanks for reporting. This is a known issue with some of the components and we have handled it in all of our deployment methods. If you are using your own installation mechanism, you can see the components which create and also use the crd in their manifests [e.g.](https://github.com/awslabs/kubeflow-manifests/blob/main/tests/e2e/resources/installation_config/cognito-rds-s3.yaml#L87) (see the ones which have crds). Please install these component once, wait for the crd to be available and reapply for the installation to complete
