### ISSUE TITLE
Can not select namespace in central dashboard

### ISSUE THREAD

**Issue by xd-dante** [awslabs/kubeflow-manifests#529]
**Describe the bug**
Can not select namespace in the central dashboard when user try to create a notebook. I have integrated Cognito and created users in cognito now when user try to signing to kubeflow and try to create notebook so notebook not getting created at all due to I am not able to enter the namespace 

**Steps To Reproduce**

**Expected behavior**
Ideally when I create a user in Cognito and that users try to sign in kubeflow they can create their own notebook with namespace they want to create.

**Environment**
* Kubernetes version 2.13.1
* Using EKS (yes/no), if so version? 1.22
* Kubeflow version 1.6.1
* AWS build number 
* AWS service targeted (S3, RDS, etc.) S3 RDS Cognito

**Screenshots**
![Uploading image.png…]()

**Additional context**
I have used terraform to deploy this stack

**Comment by surajkota** [comment]
Hi @xd-dante, what method did you use to install Kubeflow? can you check if you have an envoy filter named `kubeflow-userid`

```
 kubectl get envoyfilter -n istio-system kubeflow-userid
```

**Comment by xd-dante** [comment]
@surajkota Thanks for replying i just deployed stack as it is using terraform can you tell me where I need to create this profile using terraform version of deployment?

 ` kubectl get envoyfilter -n istio-system kubeflow-userid`
 
Output:
`NAME              AGE
kubeflow-userid   6d7h`

**Comment by surajkota** [comment]
Automatic profile creation is disabled by default. If you want to enable it you can set the `CD_REGISTRATION_FLOW` variable to `true` in the `centraldashboard-parameters` configmap in `kubeflow` namespace and

Next, restart the central dashboard deployment using following command
`kubectl rollout restart deployment centraldashboard -n kubeflow`

**Comment by surajkota** [comment]
Looks like we chatted about this offline and issue is resolved. Closing this issue
