### ISSUE TITLE
AWS Kubeflow installation issues -  Failed to install oidc-authservice, timed out waiting for the condition on pods/authservice-0

### ISSUE THREAD

**Issue by nandanalluri** [awslabs/kubeflow-manifests#530]
I am trying to install AWS Kubeflow distribution following the steps mentioned in the below document and I am seeing the below issues
https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide/

==========Installing oidc-authservice==========
Release "oidc-authservice" has been upgraded. Happy Helming!
NAME: oidc-authservice
LAST DEPLOYED: Mon Dec 19 18:53:56 2022
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
error: timed out waiting for the condition on pods/authservice-0
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
error: timed out waiting for the condition on pods/authservice-0
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
error: timed out waiting for the condition on pods/authservice-0
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 278, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 79, in install_kubeflow
    install_component(
  File "utils/kubeflow_installation.py", line 143, in install_component
    validate_component_installation(installation_config, component_name)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "utils/kubeflow_installation.py", line 155, in validate_component_installation
    kubectl_wait_pods(value, namespace, key)
  File "/kubeflow-manifests/tests/e2e/utils/utils.py", line 266, in kubectl_wait_pods
    assert os.system(cmd) == 0
AssertionError
Makefile:102: recipe for target 'deploy-kubeflow' failed
make: *** [deploy-kubeflow] Error 1

**Comment by ananth102** [comment]
Hi nandanalluri, which eks version are you using?

**Comment by nandanalluri** [comment]
> 

EKS verison - 1.24.

**Comment by surajkota** [comment]
Hi @nandanalluri, we havent qualified Kubeflow-1.6 yet on EKS-1.24 and would recommend using 1.23 but to address your issue, make sure you have the EBS CSI driver installed. It is a requirement starting 1.23 and above - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23. You can verify if this is causing the problem by checking if the pvc status is Pending `kubectl get pvc -n -A`

we have highlighted this in our docs - https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/#create-eks-cluster-using-eksctl

**Comment by surajkota** [comment]
Downgrading to 1.23 resolved the issue

**Comment by richwolf817** [comment]
Downgraded to 1.23 and still having the same issue.

**Comment by surajkota** [comment]
@richwolf817 recommend opening a new issue and use bug template to get support. Highly encourage using Kubeflow 1.7

**Comment by thinksanky** [comment]
Same issue! It works on one machine and does not on the other EC2. May be it is an issue with Ec2 ? What is the path to debug logs ?

**Comment by JohnnyChin** [comment]
same issue still happening in k8s `1.25` , kubeflow `release-v1.7.0-aws-b1.0.3` even with latest ebs csi driver installed
`aws-ebs-csi-driver      v1.30.0-eksbuild.1`

**Comment by goakshit** [comment]
Running into the same issue as @JohnnyChin!
