### ISSUE TITLE
Amazon EKS and Kubeflow Compatibility

### ISSUE THREAD

**Issue by tejarora** [awslabs/kubeflow-manifests#544]
On 1/16, this page https://awslabs.github.io/kubeflow-manifests/docs/about/eks-compatibility/ had kubeflow v1.6 with kubernetes 1.23 matching compatible version.

Today 1/17, this page has removed v1.6 and the latest mentioned is v1.5

Why do you renege documentation like this without any notes/explanation???? This is irresponsible. I was in the middle of setting things up and now I have to start all over again...

**Comment by ananth102** [comment]
Hi tejarora, thanks for informing us about the website bug, it should be fixed now.

**Comment by surajkota** [comment]
Hi @tejarora, thanks for reporting the issue. It happened by mistake on our side while adding search functionality to the website and back-porting the feature. We have fixed the issue now. Hopefully you can continue your deployment. Please let us know if you face any issues while deploying.
