### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by tejarora** [awslabs/kubeflow-manifests#545]
This page https://awslabs.github.io/kubeflow-manifests/docs/deployment/prerequisites/ asks that EKS be setup as a prerequisite
However, the terraform deployment option automatically creates EKS. And that page also refers to THIS prerequisite... 

There's an inconsistency here!!!

This documentation was updated around 1/16-1/17 and messed up after that... It was fine when I saw it a day ago

**Comment by ananth102** [comment]
Website has been fixed.
