### ISSUE TITLE
How can embedded code in the ConfigMap be regenerated from an updated upstream?

### ISSUE THREAD

**Issue by blair-anson** [awslabs/kubeflow-manifests#556]
I have noticed that in `kubeflow-pipelines-profile-controller-code-dhffkh7f55-kubeflow-ConfigMap.yaml` 
https://github.com/awslabs/kubeflow-manifests/blob/main/charts/apps/kubeflow-pipelines/rds-s3/templates/ConfigMap/kubeflow-pipelines-profile-controller-code-dhffkh7f55-kubeflow-ConfigMap.yaml

there is embedded code from the upstream repo here (once the kubeflow-manifests project is added)
`upstream/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py`

Is there a build command that will regenerate the contents of  `kubeflow-pipelines-profile-controller-code-dhffkh7f55-kubeflow-ConfigMap.yaml` based on updates to the sync.py file in the upstream folder?
I could update it manually but if there are more embeds of code in the helm charts then using a provided command would make more sense.

**Comment by ryansteakley** [comment]
Hello blair-anson, our hosted version of the specific sync.py file is not the same as the one that lives in the upstream it has been slightly modified to support KFP Visualizations and Artifact Store with S3 as source.  It is actually based off of the one that lives here https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/apps/pipeline/s3/sync.py.  Currently we do not have automation for re-generating that specific file based off of the upstream.

**Comment by blair-anson** [comment]
Thanks!
