### ISSUE TITLE
Cognition automatic script does not work when root domain is managed outside Route53.

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#560]
**Describe the bug**
The autonated script for Cognito does not support the use case where the root domain is outside of Route53 but the subdomain is in Route53.
The script also requires human intervention which is not suitable for CI/CF environments.

**Steps To Reproduce**
1. Install using automated script

**Expected behavior**
I expect the script to allow to pass the necessary flags to handle such use cases.

**Environment**
* Kubernetes version 1.21
* Using EKS (yes/no), if so version?
* Kubeflow version 1.6.1
* AWS build number
* AWS service targeted (S3, RDS, etc.) RDS Cognito S3

**Additional context**
I can contribute to this improvement.

**Comment by jsitu777** [comment]
Hi @AlexandreBrown , the automatic script does assume route 53 info and it's grabbing and generating the info from the config.yaml file https://github.com/awslabs/kubeflow-manifests/blob/main/tests/e2e/utils/cognito_bootstrap/config.yaml 

You may try the mannual guide if you are not using Route53 for your domain:
-https://awslabs.github.io/kubeflow-manifests/main/docs/deployment/cognito/manifest/guide/
-https://awslabs.github.io/kubeflow-manifests/main/docs/add-ons/load-balancer/guide/#create-domain-and-certificates

**Comment by AlexandreBrown** [comment]
Hello @jsitu777 , do you think we could modify the script to support the use case where the root domain is outside of Route53? Also we need a script that can be used in CI environment (no user interaction).

**Comment by AlexandreBrown** [comment]
@jsitu777 @ryansteakley @surajkota Let me know if you guys think this would be possible, I can contribute to this improvement.

**Comment by surajkota** [comment]
Hi Alexandre, what do you think about using terraform instead?

We are planning to use terraform instead of these scripts eventually. Scripts are error prone to timeouts/retrys and need additional code to maintain state

**Comment by AlexandreBrown** [comment]
@surajkota Ok, will look into the terraform deployment option instead.  
I will close this as a "won't do" and let's put our efforts into the terraform deployment option then.  
Thanks for your feedback Suraj :+1:
