### ISSUE TITLE
Cloudwatch integration with Kubeflow

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#59]
**Describe the bug**
Worker node group logging described [here](https://v1-2-branch.kubeflow.org/docs/aws/logging/) can be used for sending pods log to cloud watch. However with the current setup it does not work. For e.g. the permission which we assign to worker node does not have policy to `describe log group` from cloud watch. 

**Steps To Reproduce**
1. goto folder `kubeflow-manifests/distributions/aws/fluentd-cloud-watch` and update the `base/params.env` values. 
2. run `kubectl apply -k fluentd-cloud-watch/base
3. Check the cloudwatch to see if it has log group `/aws/containerinsights/${AWS_CLUSTER_NAME}/containers` 
4. you can see the logs from `fluentd-cloudwatch-xxxxx` pods and it will report errors like below
```
2021-12-26 06:03:51 +0000 [warn]: #0 [out_cloudwatch_logs_containers] failed to flush the buffer. retry_time=7 next_retry_seconds=2021-12-26 06:05:02 +0000 chunk="5d4065628678b563f9dd8c2962ea5455" error_class=Aws::CloudWatchLogs::Errors::AccessDeniedException error="User: arn:aws:sts::<my account_id>:assumed-role/eksctl-myclustername-nodegroup-li-NodeInstanceRole-PP7XWJ1Q1DWU/i-01083ed00c1fdfdff6 is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:us-east-1:<my_aws_account_id>:log-group::log-stream:"
  2021-12-26 06:03:51 +0000 [warn]: #0 suppressed same stacktrace
```  

**Expected behavior**
No error message in fluentd pods 
cw log group should be created and pods log should be pushed there

**Environment**
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version?  yes
* AWS service targeted (S3, RDS, etc.): cloud watch

**Screenshots**

**Additional context**

**Comment by surajkota** [comment]
The fluentd service account in the `kube-system` namespace needs to be annotated with a role with these permissions - https://github.com/awslabs/kubeflow-manifests/blob/v1.3-branch/distributions/aws/infra_configs/iam_cloudwatch_policy.json. I see it missing in the steps to reproduce

Triage with the following additional steps:

```
export CLUSTER_NAME=
export CLUSTER_REGION=
export AWS_ACCOUNT_ID=

aws iam create-policy \
    --policy-name cloudwatch_access_policy \
    --policy-document file://distributions/aws/infra_configs/iam_cloudwatch_policy.json

eksctl create iamserviceaccount \
    --name fluentd \
    --namespace kube-system \
    --cluster $CLUSTER_NAME \
    --attach-policy-arn arn:aws:iam::$AWS_ACCOUNT_ID:policy/cloudwatch_access_policy \
    --approve \
    --override-existing-serviceaccounts \
    --region $CLUSTER_REGION
```

**Comment by ryansteakley** [comment]
Fluentd is no longer reccomended by Amazon EKS and they will be deprecating it in favor of fluentbit. In respect to the above error that occurred if using fluentd, this error message occurs becuase of a lack of permission to the NodeInstanceRole, which can be remedied by providing it with the proper iam policy as documented here https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-prerequisites.html
`CloudWatchAgentServerPolicy` needs to be attached to the role  `arn:aws:sts::<my account_id>:assumed-role/eksctl-myclustername-nodegroup-li-NodeInstanceRole-PP7XWJ1Q1DWU/i-01083ed00c1fdfdff6 `  which contains the following permissions.

>  "cloudwatch:PutMetricData",
                        "ec2:DescribeVolumes",
                        "ec2:DescribeTags",
                        "logs:PutLogEvents",
                        "logs:DescribeLogStreams",
                        "logs:DescribeLogGroups",
                        "logs:CreateLogStream",
                        "logs:CreateLogGroup"

This would resolve the error `is not authorized to perform: logs:DescribeLogGroups` that we see above
