### ISSUE TITLE
Not able to access the model server url externally

### ISSUE THREAD

**Issue by infa-saka** [awslabs/kubeflow-manifests#599]
Not able to access the model server url externally

Sample used from the example,
https://kserve.github.io/website/0.8/get_started/first_isvc/#2-create-an-inferenceservice

**Comment by surajkota** [comment]
Please list the steps to replicate
Have you followed this guide?

https://awslabs.github.io/kubeflow-manifests/docs/component-guides/kserve/tutorial/

**Comment by ananth102** [comment]
Issue was due to Authorization policy not being present. We should include it in the docs.

**Comment by ryansteakley** [comment]
@ananth102 can you clarify what you mean by Authorization policy not being present? Does the docs not specifically mention https://awslabs.github.io/kubeflow-manifests/docs/component-guides/kserve/tutorial/#create-an-authorizationpolicy to create one?

**Comment by ananth102** [comment]
@ryansteakley The Authorization policies here: https://github.com/awslabs/kubeflow-manifests/issues/82#issuecomment-1068641378 were not applied. Our website has a link to it but maybe it should be more explicit.
