### ISSUE TITLE
JQ version Error

### ISSUE THREAD

**Issue by techwithshadab** [awslabs/kubeflow-manifests#605]
**Describe the bug**
JQ version given in makefile available in kubeflow-manifests folder is not getting installed

**Steps To Reproduce**
Run the command `make install-tools` in `kubeflow-manifests` directory

**Expected behavior**
It should successfully install all the tools

**Screenshots**
Error message:
```
E: Version '1.5+dfsg-2' for 'jq' was not found
make: *** [Makefile:41: install-jq] Error 100
```

**Comment by ananth102** [comment]
Can you run `sudo apt update`

**Comment by jbgerth** [comment]
Which version of Ubuntu/Debian are you using? The version of `jq` will work for Ubuntu 20.04. If you are using for example 22.04, you will need to bump the version of `jq` to 1.6.

I think as a long-term solution the `jq` version does not need to be pinned in the `Makefile` or the OS could be checked at the beginning of the file, to choose the version more dynamically.

**Comment by koseoyoung** [comment]
Hi, I'm having the same issue. My machine info: Ubuntu 20.04 and my `jq` version is 1.6.

```
ubuntu@ip-172-31-8-61:~/kubeflow-manifests$ jq --version
jq-1.6
```
When I try `make install-docs`, this happens: Any thoughts? 

```
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5368912 (5.1M) [application/octet-stream]
Saving to: ‘STDOUT’

-                             100%[===============================================>]   5.12M  27.5MB/s    in 0.2s

2023-04-07 22:46:38 (27.5 MB/s) - written to stdout [5368912/5368912]

sudo mv yq_linux_amd64 /usr/bin/yq
rm install-man-page.sh
rm yq.1
yq --version
yq (https://github.com/mikefarah/yq/) version 4.26.1
sudo apt-get install jq=1.5+dfsg-2 -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '1.5+dfsg-2' for 'jq' was not found
make: *** [Makefile:41: install-jq] Error 100
```

**Comment by surajkota** [comment]
should be resolved as part of https://github.com/awslabs/kubeflow-manifests/pull/698
