### ISSUE TITLE
Kubeflow Pipeline does not work for Kubeflow 1.7 Terraform when using other region than us-east-1

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#628]
**Describe the bug**
Bug is identical to https://github.com/awslabs/kubeflow-manifests/issues/148

**Steps To Reproduce**
1. Create a run using the pipeline sample that comes with Kubeflow : `[Tutorial] Data passing in python components`  

**Expected behavior**
I expect the pipeline to succeed.

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version? `1.24`
* Kubeflow version `1.7 RC-2`
* AWS build number : aws main using the latest commit (`e2ae7bc2d4acf73190e86d6b99c2b1b3aee5b0d1`) from this PR currently opened : https://github.com/awslabs/kubeflow-manifests/pull/613
* AWS service targeted (S3, RDS, etc.) `COGNITO-RDS-S3 using terraform`

**Screenshots**
![image](https://user-images.githubusercontent.com/26939775/226075522-8ee22a77-0863-4c05-85d9-1a111190d19f.png)
**Additional context**  
Even tho the policy has S3 full access, after seeing the failure, I tried to manually add the following policy to the role that gets created during the deployment but it did not fix the issue (not a shocker since full s3 access should already have everything):  
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::kf-artifact-store-20230318000439418600000004"
        }
    ]
}
```  
![image](https://user-images.githubusercontent.com/26939775/226075635-3f6d530b-0a2e-419c-b2a9-34a3e7407da4.png)

**Comment by ryansteakley** [comment]
Hey @AlexandreBrown, does your trust relationship include the service account that is running the sample pipeline? i.e(the one in kubeflow-user-example-com) That portion is not automated as of now.

**Comment by AlexandreBrown** [comment]
@ryansteakley what do you mean by trust relationship exactly?

I got this error by installing a fresh install without modifying S3 permissions (so using the IRSA role that gets created). I got the error on the default namespace (`kubeflow-user-example-com` )

**Comment by ryansteakley** [comment]
Yes the default namespace kubeflow-user-example-com uses a service-account named default-editor, this needs to be part of the policy. Currently the code only adds ml-pipeline in the kubeflow namespace. This is because the profile-addon will create the necessary policy if used when creating additional namespace. The default namespace, still working on adding chart/yaml for supporting it.

**Comment by AlexandreBrown** [comment]
Ok so if I create a new namespace following the doc, then the add-on will make it work?

**Comment by ryansteakley** [comment]
Yes if using the profile add-on it will add all the necessary things to make it work. Will make changes so that the kubeflow-user-example-com will work by default as well. Will update those docs.

**Comment by AlexandreBrown** [comment]
@ryansteakley Awesome, then in that can I will close this issue.  
Thank you
