### ISSUE TITLE
change the image registry for container images from `k8s.gcr.io` to `registry.k8s.io`

### ISSUE THREAD

**Issue by tejarora** [awslabs/kubeflow-manifests#636]
**Describe the bug**
k8s.gcr.io registry is being retired. Your manifests use this registry.
See this announcement https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

Also provide steps in your documentation for those who have used your manifests on how to update their clusters.

**Steps To Reproduce**

**Expected behavior**

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version?
* Kubeflow version
* AWS build number
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

**Additional context**

**Comment by surajkota** [comment]
Hi, thanks for opening the issue. We have identified that we have one component using this registry - `secrets-store-csi-driver `. Existing deployments wont be affected as of now but the guidance is to start using the new registry as soon as possible, all the old images are available in the new registry.

We will be providing guidance on how to update existing deployment deployments. Thank you for your patience in the meantime.

**Comment by ryansteakley** [comment]
This only effects csi-secrets-driver for those who have installed either RDS-S3/Cognito-RDS-S3. To update your pulled image source run the following kubectl commands

```
kubectl set image daemonset/csi-secrets-store node-driver-registrar=registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.3.0 -n kube-system
kubectl set image daemonset/csi-secrets-store secrets-store=registry.k8s.io/csi-secrets-store/driver:v1.0.0-rc.1 -n kube-system
kubectl set image daemonset/csi-secrets-store liveness-probe=registry.k8s.io/sig-storage/livenessprobe:v2.4.0 -n kube-system
```
