### ISSUE TITLE
Issue while installing kubeflow on eks

### ISSUE THREAD

**Issue by schikkam** [awslabs/kubeflow-manifests#637]
**Describe the bug**
Kubeflow installation always failed at isio installation section:
==========Installing istio-1-14==========

**Steps To Reproduce**
Followed the documentation in the same order: 
1. https://awslabs.github.io/kubeflow-manifests/docs/deployment/prerequisites/#docker
2. https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/

**Expected behavior**
Should install s/w.

**Environment**
* $ kubectl version --short
Client Version: v1.22.6-eks-7d68063
Server Version: v1.22.17-eks-48e63af

* Using EKS (yes/no), if so version? Yes
* Kubeflow version :v1.6.1
* AWS build number
* AWS service targeted (S3, RDS, etc.) - S3
**Screenshots**
![image](https://user-images.githubusercontent.com/1320501/227866276-3a43aa67-8c56-4715-9bc5-68212e667036.png)

**Additional context**

**Comment by surajkota** [comment]
hi @schikkam, what version of EKS are you using? and installation method? - kustomize/helm
Are you using one of the tested versions?
https://awslabs.github.io/kubeflow-manifests/docs/about/eks-compatibility/

**Comment by sawanverma** [comment]
Hi @surajkota He has mentioned the versions already. EKS - 1.22 and Kubeflow 1.6

**Comment by schikkam** [comment]
Hi @surajkota ,  Please let me know if you need any further details.  Looking forward to your response!

**Comment by surajkota** [comment]
Closing due to no response
