### ISSUE TITLE
Add Mac support to deploy kubeflow on remote K8s cluster

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#640]
**What is the URL of the document?**
[Kubeflow deployment option](https://awslabs.github.io/kubeflow-manifests/docs/deployment/prerequisites/)

**Which section(s) is the issue in?**
I would like to see Mac as a gateway node to deploy kubeflow on EKS (or any other k8s) cluster. 

**What needs fixing and describe the solution you'd like?**
It should cover pre-requisite and command to install (at least vanila) kubeflow on remote EKS/k8s cluster.

**Additional context**

**Comment by renanmb** [comment]
Just dont use Mac. Also you can use Cloud9 to do everything.

**Comment by surajkota** [comment]
We recommend using container image to deploy from Mac, closing this as not planned for now. We will reevaluate this in future
