### ISSUE TITLE
Document Kubeflow Pipeline v2 credentials setup

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#650]
**What is the URL of the document?**
The URL to help identify the document.

**Which section(s) is the issue in?**
The sections(s) within the document that have issue in.

**What needs fixing and describe the solution you'd like?**
A clear and concise description of what the issue is.

**Additional context**

**Comment by ryansteakley** [comment]
Editing this internally now

**Comment by surajkota** [comment]
resolved as part of https://github.com/awslabs/kubeflow-manifests/pull/680
