### ISSUE TITLE
Terraform Vanilla deployment fails

### ISSUE THREAD

**Issue by RegaliaXYZ** [awslabs/kubeflow-manifests#663]
**Describe the bug**
make deploy is failing at the deploy-kubeflow-components

**Steps To Reproduce**
`export KUBEFLOW_RELEASE_VERSION=v1.6.1
export AWS_RELEASE_VERSION=v1.6.1-aws-b1.0.1
git clone https://github.com/awslabs/kubeflow-manifests.git && cd kubeflow-manifests
git checkout ${AWS_RELEASE_VERSION}
git clone --branch ${KUBEFLOW_RELEASE_VERSION} https://github.com/kubeflow/manifests.git upstream

Replace versions to v4.27.0 as the current one does not pass the terraform init

make deploy
Specify 1.25 as the eks version for everything`

**Expected behavior**
Terraform successfully finishes and the kubeflow cluster is properly created

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version? yes, 1.25
* Kubeflow version v1.6.1
* AWS build number v1.6.1-aws-b1.0.1
* AWS service targeted (S3, RDS, etc.) vanilla

**Screenshots**

![image](https://user-images.githubusercontent.com/17549537/230335489-4176764b-803e-433b-a3ab-25e8bf00f68a.png)

**Comment by ananth102** [comment]
Hi RegaliaXYZ The policy/v1beta1 API version of PodDisruptionBudget is no longer served as of v1.25.  https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

**Comment by RegaliaXYZ** [comment]
Are there any plans to update the terraform manifests to be compliant with 1.25? There should be a warning at least on the official docs that the terraform manifests don't work with the versions provided in the docs

**Comment by ananth102** [comment]
We list the compatible eks versions here https://awslabs.github.io/kubeflow-manifests/docs/about/eks-compatibility/

**Comment by surajkota** [comment]
1.25 will be supported starting 1.7 release
