### ISSUE TITLE
there is no 'make port-forward'

### ISSUE THREAD

**Issue by ssilb4** [awslabs/kubeflow-manifests#687]
**Describe the bug**
in [documents](https://awslabs.github.io/kubeflow-manifests/docs/deployment/connect-kubeflow-dashboard/#port-forward-terraform-deployment), run ```make port-forward```. but in Makefile, there is no port-forward.

After I ran ```kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80```,  I can access using ssh.

**Steps To Reproduce**

**Expected behavior**

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version? yes
* Kubeflow version
* AWS build number
* AWS service targeted (S3, RDS, etc.) 
I just follow https://awslabs.github.io/kubeflow-manifests/docs/deployment/prerequisites/
vanila
export KUBEFLOW_RELEASE_VERSION=v1.6.1
export AWS_RELEASE_VERSION=v1.6.1-aws-b1.0.2

**Screenshots**

**Additional context**

**Comment by ryansteakley** [comment]
Are you running make port-forward from the root directory of kubeflow-manifests?

**Comment by ssilb4** [comment]
oh I see.

in [document](https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide-terraform/), It say ```cd deployments/vanilla/terraform```

It confuse me.

**Comment by ryansteakley** [comment]
@ssilb4 will make some changes to docs to clarify this.

**Comment by surajkota** [comment]
resolved as part of https://github.com/awslabs/kubeflow-manifests/pull/699
