### ISSUE TITLE
Error: secret "mlpipeline-minio-artifact"/"mysql-secret" not found in some deployments

### ISSUE THREAD

**Issue by lnguyen46** [awslabs/kubeflow-manifests#69]
**Describe the bug**
Error: secret "mlpipeline-minio-artifact" not found in the following deployments:
  - ml-pipeline-ui
  - kubeflow-pipelines-profile-controller
  - minio
  
Error: secret "mysql-secret" not found in the following deployments:
  - metadata-grpc-deployment
  - ml-pipeline
  - cache-server

It seems that these secrets are removed in file `disable-default-secrets.yaml` in commit 6fdcc9b0d8206c00b9fa1e6491aeab310bd47df4 but still got used in a lot of deployments.

**Steps To Reproduce**

- Deploying with `distributions/aws/examples/rds-s3` templates. 
- ```kubectl describe pod -n kubeflow $(kubectl get pod -n kubeflow -l app=ml-pipeline-ui -o jsonpath="{.items[0].metadata.name}") ```  

**Expected behavior**
Above deployments run successfully.

**Environment**
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version?  Yes, EKS version: eks.7
* AWS service targeted (S3, RDS, etc.) -> s3-rds

**Screenshots**
None

**Additional context**
I deploy with this custom kustomization.yaml which is based on `distributions/aws/examples/rds-s3` but is modified to use only necessary services based on my own need

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Istio
- ../common/istio-1-9/istio-crds/base
- ../common/istio-1-9/istio-namespace/base
- ../common/istio-1-9/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-9/kubeflow-istio-resources/base

# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/istio
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# User namespace
- ../common/user-namespace/base

# Configured for AWS RDS and AWS S3

# AWS Secret Manager
- ../distributions/aws/aws-secrets-manager/base
# Kubeflow Pipelines
- ../apps/pipeline/upstream/env/aws
```

**Comment by bankbiz** [comment]
I found an error for `kubeflow-secrets-pod`:

`MountVolume.SetUp failed for volume "s3-secret" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod kubeflow/kubeflow-secrets-pod, err: rpc error: code = Unknown desc = Invalid JSON used with jmesPath in secret: rds-secret.`

There're any thing wrong with jmesPath? at `kubeflow-manifests/distributions/aws/aws-secrets-manager/base/secrets-manager.yaml`


Environment:
Kubernetes version: 1.21
EKS version: eks.4
AWS service targeted: cognito-s3-rds
Branch: v1.3-branch

**Comment by ryansteakley** [comment]
@bankbiz  I don't believe there is any issue, have you created the secrets in AWS-secrets manager and have not modified the `secrets-manager.yaml` in anyway?

**Comment by AlexandreBrown** [comment]
@bankbiz  Perhaps the issue "Invalid JSON" might suggest the json you sent to the secrets manager was not in the format accepted by the  kubeflow-secrets-pod ?  
I got a similar issue once when I had one field in my json as "port" : 123 instead of "port" : "123".  
The secrets manager accepts it but when came time for the db pod to read it then it screamed at me for the wrong json. Maybe your issue is something similar.  
  
If so then maybe [this PR](https://github.com/awslabs/kubeflow-manifests/pull/78) could help you set it up automatically to avoid any manual entry error

**Comment by surajkota** [comment]
@bankbiz I ran into the same issue today and realized the secret values were not getting set properly as Alex mentioned. Can you check the Secret value in `rds-secret` and `s3-secret` from Secrets manager?

In my case the s3 secret values were null:
![Screenshot 2022-02-11 at 7 06 27 PM](https://user-images.githubusercontent.com/22246703/153694340-e66efa16-5a72-47e2-840d-8832d8290604.png)

**Comment by bankbiz** [comment]
Yeah! I found that the secret is not set properly. Alex PR cloud help for future release.

Thanks.

**Comment by surajkota** [comment]
@lnguyen46 Closing this issue since we haven't heard back since the issues was opened. Please re-open if you still need assistance.
