### ISSUE TITLE
"node(s) had volume node affinity conflict" when launching notebook with multiple volumes

### ISSUE THREAD

**Issue by brsolomon-deloitte** [awslabs/kubeflow-manifests#711]
I'm reposting an issue from upstream `kubeflow/kubeflow` here as it is specific to Kubeflow on AWS. All details can be found there.

https://github.com/kubeflow/kubeflow/issues/7109

**Comment by ryansteakley** [comment]
Hello thanks for the issue. This is something we will look into to determine if it is a bug or a feature request.

**Comment by surajkota** [comment]
An EBS volume and the instance to which it attaches must be in the same Availability Zone. This is a requirement from the [EBS service side](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-attaching-volume.html). From the Kubeflow side, there nothing that can be done at the moment to change this but following are a few options/recommendations:

EKS supports other storage backends that could be used zone independently, with different properties (like performance, pricing etc). For example there is [AWS EFS](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) that can be used in any AZ within an AWS region.

That being said, using EBS is a common option with Kubernetes PVs if you can:
- [Spin up pods/notebook instances in same AZ using using node affinity or nodeSelector](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/)
- [Create a custom StorageClass to specify the zones where volumes are created](https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies)
- Setup a nodegroup + Autoscaling for nodes in that AZ

Hope this helps. Let us know if you more information in any of the above options.
