### ISSUE TITLE
[Feedback requested] Add ability to create one ALB per namespace for inference

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#718]
**Is your feature request related to a problem? Please describe.**
This feature request comes from a desire to have a separate ALB for increased isolation between dev, staging and prod. If this is not needed or overkill and if you believe having 1 ALB would be sufficient for all 3 stages then let me know I would like to hear your thoughts (what is the recommeded approach by AWS?).  
In our case we have 3 namespaces for inference only use cases : `dev`, `staging`, `prod` (these are not user namespaces and are there only for inference).  
The current AWS integration for KServe uses a fixed name for the ingress: `istio-ingress`.    
This makes it not possible to have a different ALB/ingress for each namespace/stage.

**Describe the solution you'd like**
Add the ability to specify a suffix for the name of the ingress eg: `istio-ingress-${NAMESPACE}` so that we can repeat the steps for each namespace.

**Comment by surajkota** [comment]
Looks like we missed responding to this issue. To clarify, for KServe we are creating a separate ingress which has name `istio-ingress-api`(not a fixed name), it can be named anything, this is just the default

Answer to other question will be based on your traffic to these isvc, if your load is too high you might have to scale the isio-ingressgateway service itself because that can become a bottleneck. If load is not high, creating a separate ALB for prod should be sufficient to isolate production traffic and audibility purpose

**Comment by AlexandreBrown** [comment]
@surajkota Thank you for your feedback.   
Where did you get the `istio-ingress-api` name? When I deployed it it took the name from here :  
https://github.com/awslabs/kubeflow-manifests/blob/a2062a7e692b90dbdec394c1b9836154fc3c6a76/awsconfigs/common/istio-ingress/overlays/api/ingress.yaml#L4  
which seems to be `istio-ingress`.    
This is also what the doc reflects:  
![image](https://github.com/awslabs/kubeflow-manifests/assets/26939775/33e6a911-1298-4b45-987d-ed946a9ec9f5)
 
If I want to create one ALB per namespace, is it the only place that I would need to change the name or is there other files depending on this exact naming?  
For instance, could I simply edit the `ingress.yaml` with the name I want and `kubectl apply` it then repeat the process for each inference namespace?

**Comment by surajkota** [comment]
Few parameters are being updated in kustomization.yaml including the name - https://github.com/awslabs/kubeflow-manifests/blob/a2062a7e692b90dbdec394c1b9836154fc3c6a76/awsconfigs/common/istio-ingress/overlays/api/kustomization.yaml#LL6-L14


You can update the name(line 14 & 22) in the kustomization.yaml and build it to see final output

**Comment by AlexandreBrown** [comment]
@surajkota ok yes my bad. I am using Cognito.
Which files exactly do I have to edit for Cognito?
Thanks

**Comment by surajkota** [comment]
I am not able to repro this
```
kustomize build awsconfigs/common/istio-ingress/overlays/api
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
apiVersion: v1
data:
  certArn: ""
  httpHeaderName: x-api-key
  httpHeaderValues: '["token1", "token2"]'
  loadBalancerScheme: internet-facing
kind: ConfigMap
metadata:
  labels:
    kustomize.component: istio-ingress
  name: istio-ingress-api
  namespace: istio-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.istio-ingressgateway: '{"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"istio-ingressgateway","ServicePort":"80","Weight":100}]}}'
    alb.ingress.kubernetes.io/certificate-arn: ""
    alb.ingress.kubernetes.io/conditions.istio-ingressgateway: '[{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName":
      "x-api-key", "Values":["token1", "token2"]}}]'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    kustomize.component: istio-ingress
  name: istio-ingress-api
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
```


```
kustomize version
v5.0.1
```

**Comment by AlexandreBrown** [comment]
@surajkota I am not able to reproduce as well.  
I've followed your suggestion and added the value substitution:  
```shell
sed -i "s/istio-ingress-api/istio-ingress-api-${INFERENCE_NAMESPACE_NAME}/g" awsconfigs/common/istio-ingress/overlays/api/kustomization.yaml \
    && kustomize build awsconfigs/common/istio-ingress/overlays/api | kubectl apply -f -
```  
It worked.  
```shell
kubectl get ingress -n istio-system
```
Output:  
```shell
NAME                    CLASS    HOSTS   ADDRESS                                                                   PORTS   AGE
istio-ingress           alb      *       k8s-istiosys-istioing-xxx-xxx.us-east-2.elb.amazonaws.com   80      135m
istio-ingress-api-dev   <none>   *       k8s-istiosys-istioing-xxx-xxx.us-east-2.elb.amazonaws.com   80      2m38s
```  
Thank you for your quick response time.
