### ISSUE TITLE
Vanilla deployment fails due to timeout in oidc-authservice

### ISSUE THREAD

**Issue by askulkarni2** [awslabs/kubeflow-manifests#739]
**Describe the bug**
I was deploying kubeflow 1.7 with provided instructions using the manifests. After reviewing the pod status, the `pods/authservice-0` continued to remain in pending status as it was not able to create a PVC. 

```sh
==========Installing oidc-authservice==========
Release "oidc-authservice" does not exist. Installing it now.
NAME: oidc-authservice
LAST DEPLOYED: Thu May 11 12:52:44 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
error: timed out waiting for the condition on pods/authservice-0
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
error: timed out waiting for the condition on pods/authservice-0
Waiting for oidc-authservice pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (authservice)' --timeout=240s -n istio-system
```

**Steps To Reproduce**

Follow vanilla deployment steps.

**Expected behavior**
Vanilla deployment should without any issues.

**Environment**
* Kubernetes version : 1.25
* Using EKS (yes/no), if so version? 1.25
* Kubeflow version: v1.7.0
* AWS build number: aws-b1.0.0
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

**Additional context**
I manually installed the EBS CSI driver and that resulted in the PV and PVC being created successfully. We should probably update the `eksctl` command [here](https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/) and make the corresponding changes in the terraform deployment as well.

**Comment by surajkota** [comment]
We have it as a step in documentation pointing to steps in EKS docs - https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/#important-if-you-are-using-an-eks-version--123-install-the-amazon-ebs-csi-driver-by-following-the-instructions-herehttpsdocsawsamazoncomekslatestuserguideebs-csihtml since eksctl did not have single line argument for this 

It is installed by default in terraform deployment.

**Comment by askulkarni2** [comment]
Oops, sorry I missed that. It is possible to launch add-ons via eksctl. See https://eksctl.io/usage/addons/.

**Comment by paravatha** [comment]
@askulkarni2 I am seeing same issue even after adding EBS CSI add on. 
It seems like, the PVC is not being created for _authservice-0_ pod in _istio-system_ namespace. So, its just in pending stage.
Did you have to do anything else after adding EBS CSI driver?

**Comment by surajkota** [comment]
@paravatha feel free to open a new issue if it is not resolved. Also, check the ebs csi driver pod logs to see if there are any errors.
