### ISSUE TITLE
Kubeflow installation on EKS should not use fixed secret names, such as "s3-secret"  or "rds-secret"

### ISSUE THREAD

**Issue by jianwu-github** [awslabs/kubeflow-manifests#74]
Hi,

Following the installation instructions at https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3, the secret names are fixed as  "s3-secret"  and "rds-secret", this would prevent multiple kubeflow installation under same AWS Account.

Please update the doc, if these secret names can be customized for each kubeflow installation.

Thanks!

**Comment by surajkota** [comment]
Hi @jianwu-github, Thanks for the feedback. I agree with the suggested enhancement. We will look into it and update this issue.

**Comment by surajkota** [comment]
Hi @jianwu-github, configuring secret names is now supported. Please see updated instructions: https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/

You need to:

- Rename the `parameters.objects.objectName` field in [the RDS Secret provider configuration](https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/common/aws-secrets-manager/rds/secret-provider.yaml) to match the secret name created

- Rename the `parameters.objects.objectName` field in [the S3 Secret provider configuration](https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/common/aws-secrets-manager/s3/secret-provider.yaml) to match the secret name created
