### ISSUE TITLE
ACK SageMaker controller crash loop when IRSA role already exists

### ISSUE THREAD

**Issue by askulkarni2** [awslabs/kubeflow-manifests#743]
**Describe the bug**
The ACK SageMaker controller goes in a crash loop when you recreate an EKS cluster with the same name without cleaning up kubeflow distribution first. This definitely is an edge case but common enough during experimentation when you need to tear up the EKS cluster a couple of time to get the right configuration with `eksctl`. I've traced it down to the controller not being able `AssumeRole` the IRSA role created for the previous deployment and not being cleaned. There is an error during the new deployment as shown below which is nice but since the deployment script doesn't terminate it could be a bit hard to figure out why the SageMaker controller is in a crash loop unless you go back in the deployment log (and know that you should do that).

```sh
kubectl get pods -n ack-system
NAME                                                        READY   STATUS   RESTARTS      AGE
ack-sagemaker-controller-sagemaker-chart-5554675c7c-zrpd9   0/1     Error    4 (45s ago)   90s
```

**Steps To Reproduce**
1. Create an EKS cluster using `eksctl`, e.g. `eksctl create -f mycluster.yaml` 
2. Deploy kubeflow using `make` command, e.g. `make deploy-kubeflow INSTALLATION_OPTION=helm DEPLOYMENT_OPTION=vanilla`
3. Delete eks cluster using `eksctl, e.g. `eksctl delete -f mycluster.yaml`
4. Recreate EKS cluster with same name, e.g. `eksctl create -f mycluster.yaml`
5. Redeploy kubeflow, e.g. `make` command, e.g. `make deploy-kubeflow INSTALLATION_OPTION=helm DEPLOYMENT_OPTION=vanilla`
6. Verify SageMaker Controller actually fails but deployment continues. e.g. 

```
=================================================================
                          Reading Config
=================================================================
=================================================================
        Create OIDC IAM role for ACK SageMaker Controller
=================================================================
INFO:botocore.credentials:Found credentials in environment variables.
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kf-ack-sm-controller-role-kubeflow-gitops already exists.
Try running cleanup_sm_controller_req.py
```

**Expected behavior**
I would like to see either a pre-flight check or a failed deployment when ACK SageMaker controller fails due to a pre-existing IAM role.

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version? 1.25
* Kubeflow version: 1.7
* AWS build number: b1.0.0
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

**Additional context**

**Comment by surajkota** [comment]
Agree, these type of issues are a pain to catch using python scripts, comprehensive state check can be done reliably using IaaC tools. Long term solution to solve these issues is to work on https://github.com/awslabs/kubeflow-manifests/issues/752 or use terraform based deployment end to end

I noticed cleanup Make command do not include `cleanup-ack-req` hence keeping this issue open to address it
https://github.com/awslabs/kubeflow-manifests/blob/main/Makefile#L106
https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide/#uninstall-kubeflow-on-aws
