### ISSUE TITLE
Update docs for EBS CSI driver addon setup

### ISSUE THREAD

**Issue by paravatha** [awslabs/kubeflow-manifests#768]
**What is the URL of the document?**
[https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/](https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/)

**Which section(s) is the issue in?**
Important: If you are using an EKS version >= 1.23 install the Amazon EBS CSI driver by following the instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html).

**What needs fixing and describe the solution you'd like?**
After you create the Cluster and enable Amazon EBS CSI driver add-on, you need to create or attach an existing _AmazonEKS_EBS_CSI_DriverRole_ IAM role to the EKS node-group
https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

**Additional context**
With out this additional step, you will run into the issue https://github.com/awslabs/kubeflow-manifests/issues/739

**Comment by paravatha** [comment]
@surajkota I can create a PR to update the doc. If that works for you, please assign this to me!
https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/

**Comment by surajkota** [comment]
Thanks, go ahead and create a PR

**Comment by paravatha** [comment]
It was my mistake!, It works if I create the cluster correctly using something like this https://github.com/weaveworks/eksctl/blob/main/examples/25-addons.yaml
