### ISSUE TITLE
Deploy RDS Doc Commands Do Not Work

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#77]
**Describe the bug**
The current doc suggests the following : 
![image](https://user-images.githubusercontent.com/26939775/150663229-f79d5e1a-5334-45e2-bc8a-c2c943410879.png)  
(https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3)  
But when trying the commands from the doc [Deploy Amazon RDS MySQL](https://www.kubeflow.org/docs/distributions/aws/customizing-aws/rds/#deploy-amazon-rds-mysql) to setup the RDS instance, the commands do not work.  

**Steps To Reproduce**
1. Create an EKS cluster
2. Try the commands listed [here](https://www.kubeflow.org/docs/distributions/aws/customizing-aws/rds/#deploy-amazon-rds-mysql)
![image](https://user-images.githubusercontent.com/26939775/150663097-8ea06995-360a-4dc9-9807-a1d85a525c22.png)  
![image](https://user-images.githubusercontent.com/26939775/150663111-d856f0bb-2e6a-4768-983b-d62bcb05026d.png)
![error](https://user-images.githubusercontent.com/26939775/150663153-d5b79c46-51e8-4c87-8549-f0e8e0b7f383.png)

**Expected behavior**
The command should return the VpcId for the first command, the list of SubnetId for the second command and the SecurityGroupId for the third command.
The returned value(s) should be only the values needed such that we can use the returned values as-is (no parsing required from user).

**Environment**
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes 1.21
* AWS service targeted (S3, RDS, etc.) RDS

**Comment by AlexandreBrown** [comment]
I was able to figure out why the commands would not work.  
Running `aws configure` I was able to notice that my preference for output format was set to `yaml`.   
I will make a PR to improve the commands so that it works regardless of your output format preference.

**Comment by khalyan** [comment]
> **Describe the bug** The current doc suggests the following : ![image](https://user-images.githubusercontent.com/26939775/150663229-f79d5e1a-5334-45e2-bc8a-c2c943410879.png) (https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3) But when trying the commands from the doc [Deploy Amazon RDS MySQL](https://www.kubeflow.org/docs/distributions/aws/customizing-aws/rds/#deploy-amazon-rds-mysql) to setup the RDS instance, the commands do not work.
> 
> **Steps To Reproduce**
> 
> 1. Create an EKS cluster
> 2. Try the commands listed [here](https://www.kubeflow.org/docs/distributions/aws/customizing-aws/rds/#deploy-amazon-rds-mysql)
>    ![image](https://user-images.githubusercontent.com/26939775/150663097-8ea06995-360a-4dc9-9807-a1d85a525c22.png)
>    ![image](https://user-images.githubusercontent.com/26939775/150663111-d856f0bb-2e6a-4768-983b-d62bcb05026d.png)
>    ![error](https://user-images.githubusercontent.com/26939775/150663153-d5b79c46-51e8-4c87-8549-f0e8e0b7f383.png)
> 
> **Expected behavior** The command should return the VpcId for the first command, the list of SubnetId for the second command and the SecurityGroupId for the third command. The returned value(s) should be only the values needed such that we can use the returned values as-is (no parsing required from user).
> 
> **Environment**
> 
> * Kubernetes version 1.21
> * Using EKS (yes/no), if so version? yes 1.21
> * AWS service targeted (S3, RDS, etc.) RDS

What if I'm still not getting the return values as what i expect it to be returned? Can you help?

**Comment by AlexandreBrown** [comment]
@khalyan Could you please share more details? What is the commands you are using, what is the output, screenshot maybe etc ?

**Comment by khalyan** [comment]
> @khalyan Could you please share more details? What is the commands you are using, what is the output, screenshot maybe etc ?

I think I'm making a mistake on the setup of EKS cluster. I'll post the example of what I'm using! 

$ eksctl create cluster --name=demo-eks-cluster --nodes=2 --region=ap-south-1
[ℹ]  using region ap-south-1
[ℹ]  setting availability zones to [ap-south-1a ap-south-1c ap-south-1b]
[ℹ]  subnets for ap-south-1a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for ap-south-1c - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for ap-south-1b - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-ae09882f" will use "ami-09c3eb35bb3be46a4" [AmazonLinux2/1.12]
[ℹ]  creating EKS cluster "demo-eks-cluster" in "ap-south-1" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-south-1 --name=demo-eks-cluster'
[ℹ]  2 sequential tasks: { create cluster control plane "demo-eks-cluster", create nodegroup "ng-ae09882f" }
[ℹ]  building cluster stack "eksctl-demo-eks-cluster-cluster"
[ℹ]  deploying stack "eksctl-demo-eks-cluster-cluster"
[ℹ]  building nodegroup stack "eksctl-demo-eks-cluster-nodegroup-ng-ae09882f"
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-ae09882f
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-ae09882f
[ℹ]  deploying stack "eksctl-demo-eks-cluster-nodegroup-ng-ae09882f"
[✔]  all EKS cluster resource for "demo-eks-cluster" had been created
[✔]  saved kubeconfig as "/Users/Bensooraj/.kube/config"
[ℹ]  adding role "arn:aws:iam::account_number:role/eksctl-demo-eks-cluster-nodegroup-NodeInstanceRole-1631FNZJZTDSK" to auth ConfigMap
[ℹ]  nodegroup "ng-ae09882f" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ng-ae09882f"
[ℹ]  nodegroup "ng-ae09882f" has 2 node(s)
[ℹ]  node "ip-192-168-30-190.ap-south-1.compute.internal" is ready
[ℹ]  node "ip-192-168-92-207.ap-south-1.compute.internal" is ready
[ℹ]  kubectl command should work with "/Users/Bensooraj/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "demo-eks-cluster" in "ap-south-1" region is ready

*Not working for me*

**Comment by surajkota** [comment]
@khalyan from this output, looks like the cluster has been created successfully. Can you please elaborate what is not working? i.e. which of the following outputs is empty/incorrect? - vpc_id, subnet_id or security group

**Comment by AlexandreBrown** [comment]
I created a PR in kubeflow/website to update the current doc see [this PR](https://github.com/kubeflow/website/pull/3121) but [this PR](https://github.com/awslabs/kubeflow-manifests/pull/78) improves the setup and would also fix this issue.
