### ISSUE TITLE
Replace Minio by S3

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#79]
**Is your feature request related to a problem? Please describe.**
We want to get rid of Minio completely from Kubeflow and use S3.

**Describe the solution you'd like**
Currently minio act as gateway to S3, one solution is to use S3 controller developed by ACK to act as gateway for S3. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ananth102** [comment]
Done in https://github.com/awslabs/kubeflow-manifests/pull/541
